# Generated by Django 5.2.6 on 2025-09-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uposlenik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('pozicija', models.CharField(max_length=100)),
                ('godine_rada', models.IntegerField()),
                ('pravo_na_godisnji', models.BooleanField(default=False)),
            ],
        ),
    ]
