# Generated by Django 5.2.6 on 2025-09-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UposleniciSkole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ucenik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('godiste', models.IntegerField()),
            ],
        ),
    ]
